// account dispatch states
export const LOAD_ACCOUNTS_FAIL = 'LOAD_ACCOUNTS_FAIL'
export const LOAD_ACCOUNTS_SUCCESS = 'LOAD_ACCOUNTS_SUCCESS'
export const LOAD_ACCOUNT_BY_ID_FAIL = 'LOAD_ACCOUNT_BY_ID_FAIL'
export const LOAD_ACCOUNT_BY_ID_SUCCESS = 'LOAD_ACCOUNT_BY_ID_SUCCESS'
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS'
export const UPDATE_ACCOUNT_FAIL = 'UPDATE_ACCOUNT_FAIL'
export const DESTROY_ACCOUNT_SUCCESS = 'DESTROY_ACCOUNT_SUCCESS'
export const DESTROY_ACCOUNT_FAIL = 'DESTROY_ACCOUNT_FAIL'
export const UPLOAD_ACCOUNT_SUCCESS = 'UPLOAD_ACCOUNT_SUCCESS'
export const UPLOAD_ACCOUNT_FAIL = 'UPLOAD_ACCOUNT_FAIL'

// Transaction dispatch states
export const LOAD_TRANSACTIONS_FAIL = 'LOAD_TRANSACTIONS_FAIL'
export const LOAD_TRANSACTIONS_SUCCESS = 'LOAD_TRANSACTIONS_SUCCESS'
export const LOAD_TRANSACTION_BY_ID_FAIL = 'LOAD_TRANSACTION_BY_ID_FAIL'
export const LOAD_TRANSACTION_BY_ID_SUCCESS = 'LOAD_TRANSACTION_BY_ID_SUCCESS'
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS'
export const DESTROY_TRANSACTION_FAIL = 'DESTROY_TRANSACTION_FAIL'
export const UPLOAD_TRANSACTION_SUCCESS = 'UPLOAD_TRANSACTION_SUCCESS'
export const UPDATE_TRANSACTION_FAIL = 'UPDATE_TRANSACTION_FAIL'
export const DESTROY_TRANSACTION_SUCCESS = 'DESTROY_TRANSACTION_SUCCESS'
export const UPLOAD_TRANSACTION_FAIL = 'UPLOAD_TRANSACTION_FAIL'

// Alert Dispatch types
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
